"""Add ``plans.prd_file`` for Forge intake PRD linkage (M3 fix-feature).

Adds a single nullable text column to the ``plans`` table that
records the absolute filesystem path of the PRD markdown file
generated by ``whilly forge intake``. Pins VAL-FORGE-005's contract
("plan.prd_file is non-empty; Path(plan.prd_file).is_file() is
True"): the column is the canonical, point-in-time fact bound to
the plan row. The ``plan.created`` event payload carries the same
path for defence-in-depth (VAL-CROSS-053 evidence query).

Why a column (vs. a join through ``events.payload->>'prd_file'``)?
-----------------------------------------------------------------
1. Stable: ``events`` is append-only and may be archived by future
   flusher policy; the ``plans.prd_file`` column is bound to the
   plan's lifetime (CASCADE on plan delete).
2. Operator-friendly: a one-line ``SELECT prd_file FROM plans
   WHERE id=$1`` returns the path; a join through ``events`` adds
   a JSONB cast and an event-type filter for no semantic gain.
3. Minimal: one nullable column, no constraints, no defaults, no
   FKs. Pre-existing rows (Forge-less plans created via ``whilly
   init`` / ``whilly plan create``) retain ``NULL`` and remain
   readable through every existing query path.

Reversibility
-------------
``downgrade()`` drops the column. After ``downgrade -1`` the schema
is byte-equal to revision 006: the column is gone, the
``alembic_version`` row points at ``006_plan_github_ref``. Pinned
by the alembic full-chain test (test_alembic_full_chain.py).

Revision ID: 007_plan_prd_file
Revises: 006_plan_github_ref
Create Date: 2026-04-30
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "007_plan_prd_file"
down_revision: str | None = "006_plan_github_ref"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Add ``plans.prd_file text NULL``.

    No server default — callers opt in by passing the absolute path
    of the generated PRD file. Pre-existing rows keep ``NULL`` (no
    backfill); the partial UNIQUE on ``github_issue_ref`` from
    migration 006 is unaffected.
    """
    op.add_column(
        "plans",
        sa.Column(
            "prd_file",
            sa.Text(),
            nullable=True,
            server_default=None,
        ),
    )


def downgrade() -> None:
    """Reverse the upgrade: drop the column.

    Strict reversibility: after ``downgrade -1`` the schema is
    byte-equal to revision 006 — the column is gone.
    """
    op.drop_column("plans", "prd_file")
