"""Add ``auth_audit`` table — append-only ledger of login outcomes.

Implements migration 025 from PRD-post-auth-hardening §Epic D, Item 11
(migration + repo only — call-site instrumentation and the admin browse UI
ship in D10/D10b). One row per ``POST /auth/login`` outcome, regardless of
success: the table is the source of truth for compliance review ("who tried
to log in as X at Y from IP Z, and did it work?") and for the lockout-trail
that the admin UI surfaces in D10.

Schema:

* ``id``         — ``BIGINT GENERATED BY DEFAULT AS IDENTITY`` PK. Modern
                   IDENTITY spelling per project convention (see migration
                   001 ``events`` table); the PRD prose says ``BIGSERIAL``
                   which is the legacy syntax for the same semantics.
* ``ts``         — TIMESTAMPTZ NOT NULL DEFAULT NOW(). When the attempt
                   was recorded. Indexed for "show me recent attempts".
* ``username``   — TEXT nullable. The submitted username, or NULL when the
                   outcome is ``missing_user`` and the submitted string was
                   itself empty or malformed (the repo still records the
                   attempt for rate-limit accounting). No FK to
                   ``users(username)`` — bad-actor probes for non-existent
                   accounts must also be auditable, and a FK would
                   silently reject those inserts.
* ``ip``         — TEXT nullable. Source IP (X-Forwarded-For aware in the
                   route layer); NULL if the proxy header is absent.
* ``user_agent`` — TEXT nullable. Truncation/normalisation is the route
                   layer's responsibility (see D10b instrumentation).
* ``outcome``    — TEXT NOT NULL with CHECK enforcing the five values
                   ('ok','bad_password','locked','rate_limited',
                   'missing_user'). The CHECK is the contract; the
                   Python-side ``AUTH_AUDIT_OUTCOMES`` constant in
                   :mod:`whilly.api.auth_audit_repo` must stay in sync.
* ``session_id`` — UUID nullable. Populated only on the ``'ok'`` branch
                   (links the audit row to the session row created by the
                   successful login). NULL for every failure outcome.

Indexes:

* ``ix_auth_audit_ts``           — (ts DESC) for the admin browse's
                                    default ordering.
* ``ix_auth_audit_username_ts``  — (username, ts DESC) for the per-user
                                    history query (`?username=X`) and for
                                    the lockout-trail UI in D10.

D11 ships these eagerly so D10's PR (which adds the browse route) does
not need a follow-up migration just for indexes.

Revision ID: 025_auth_audit
Revises: 024_user_totp_secrets
Create Date: 2026-05-18
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "025_auth_audit"
down_revision: str | None = "024_user_totp_secrets"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


AUTH_AUDIT_TABLE: str = "auth_audit"
AUTH_AUDIT_TS_INDEX: str = "ix_auth_audit_ts"
AUTH_AUDIT_USERNAME_TS_INDEX: str = "ix_auth_audit_username_ts"


def upgrade() -> None:
    op.create_table(
        AUTH_AUDIT_TABLE,
        sa.Column(
            "id",
            sa.BigInteger(),
            sa.Identity(always=False, start=1),
            primary_key=True,
        ),
        sa.Column(
            "ts",
            postgresql.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
        sa.Column("username", sa.Text(), nullable=True),
        sa.Column("ip", sa.Text(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("outcome", sa.Text(), nullable=False),
        sa.Column("session_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.CheckConstraint(
            "outcome IN ('ok', 'bad_password', 'locked', 'rate_limited', 'missing_user')",
            name="ck_auth_audit_outcome_valid",
        ),
    )
    op.create_index(AUTH_AUDIT_TS_INDEX, AUTH_AUDIT_TABLE, [sa.text("ts DESC")])
    op.create_index(
        AUTH_AUDIT_USERNAME_TS_INDEX,
        AUTH_AUDIT_TABLE,
        ["username", sa.text("ts DESC")],
        postgresql_where=sa.text("username IS NOT NULL"),
    )


def downgrade() -> None:
    op.drop_index(AUTH_AUDIT_USERNAME_TS_INDEX, table_name=AUTH_AUDIT_TABLE)
    op.drop_index(AUTH_AUDIT_TS_INDEX, table_name=AUTH_AUDIT_TABLE)
    op.drop_table(AUTH_AUDIT_TABLE)
