"""Add ``webauthn_credentials`` table — admin passkey enrolments (E15).

Implements migration 026 from PRD-post-auth-hardening §Epic E, Item 15
(WebAuthn / passkeys). One row per enrolled authenticator credential. The
table ships unconditionally so the schema stays portable, but the routes
that touch it (:mod:`whilly.api.webauthn_routes`) only mount when
``WHILLY_WEBAUTHN_ENABLED=1`` and only then import the optional ``webauthn``
package — mirroring the 024/TOTP precedent.

Schema:

* ``id``            — ``BIGINT GENERATED BY DEFAULT AS IDENTITY`` PK. Modern
                      IDENTITY spelling per project convention (matches 025).
* ``username``      — TEXT NOT NULL, FK → ``users(username)`` ON DELETE
                      CASCADE. The ``users`` PK is ``username`` (migration
                      020 — there is no integer ``id`` column), so the
                      credential binds to exactly one user row (security gate
                      #4) and is removed automatically when the user is
                      deleted. Mirrors how ``user_totp_secrets`` keys on
                      username, but adds the real FK that TOTP omitted.
* ``credential_id`` — BYTEA NOT NULL UNIQUE. The authenticator's credential
                      ID (raw bytes). UNIQUE because assertion verification
                      looks a credential up by this value across all users; a
                      collision would be a cloned/forged credential.
* ``public_key``    — BYTEA NOT NULL. COSE-encoded public key returned by the
                      registration ceremony; used to verify later assertions.
* ``sign_count``    — BIGINT NOT NULL DEFAULT 0. Authenticator signature
                      counter. The verify path rejects an assertion whose
                      returned counter does not advance past the stored value
                      (security gate #3 — cloned-credential detection).
* ``transports``    — TEXT[] NULL. Hints (``usb``/``nfc``/``ble``/
                      ``internal``/...) echoed back to the browser so it can
                      prompt for the right transport. Advisory only.
* ``created_at``    — TIMESTAMPTZ NOT NULL DEFAULT NOW(). When enrolled.
* ``last_used_at``  — TIMESTAMPTZ NULL. Bumped on each successful assertion;
                      surfaces "stale key" review in the future admin UI.

Indexes:

* ``ix_webauthn_credentials_username`` — (username) for the per-user fetch
  the begin-authentication ceremony issues (build ``allow_credentials``).

Revision ID: 026_webauthn_credentials
Revises: 025_auth_audit
Create Date: 2026-05-21
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "026_webauthn_credentials"
down_revision: str | None = "025_auth_audit"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


WEBAUTHN_CREDENTIALS_TABLE: str = "webauthn_credentials"
WEBAUTHN_CREDENTIALS_USERNAME_INDEX: str = "ix_webauthn_credentials_username"


def upgrade() -> None:
    op.create_table(
        WEBAUTHN_CREDENTIALS_TABLE,
        sa.Column(
            "id",
            sa.BigInteger(),
            sa.Identity(always=False, start=1),
            primary_key=True,
        ),
        sa.Column("username", sa.Text(), nullable=False),
        sa.Column("credential_id", sa.LargeBinary(), nullable=False),
        sa.Column("public_key", sa.LargeBinary(), nullable=False),
        sa.Column("sign_count", sa.BigInteger(), nullable=False, server_default=sa.text("0")),
        sa.Column("transports", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
        sa.Column("last_used_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["username"],
            ["users.username"],
            name="fk_webauthn_credentials_username",
            ondelete="CASCADE",
        ),
        sa.UniqueConstraint("credential_id", name="uq_webauthn_credentials_credential_id"),
    )
    op.create_index(
        WEBAUTHN_CREDENTIALS_USERNAME_INDEX,
        WEBAUTHN_CREDENTIALS_TABLE,
        ["username"],
    )


def downgrade() -> None:
    op.drop_index(WEBAUTHN_CREDENTIALS_USERNAME_INDEX, table_name=WEBAUTHN_CREDENTIALS_TABLE)
    op.drop_table(WEBAUTHN_CREDENTIALS_TABLE)
