"""Add opt-in local swarm tables (``whilly swarm``).

The local swarm reuses Whilly's ``plans`` / ``tasks`` queue for scheduling and
state transitions. These tables only hold swarm-specific metadata that the
generic queue has no columns for:

* ``swarm_sessions``        — one persistent conversation, its Whilly plan,
                              the applied plan revision and the single
                              coordinator lease (duplicate coordinators are
                              refused by a conditional UPDATE on this row).
* ``swarm_plan_revisions``  — revisioned structured plans proposed in the
                              conversation. Invalid plans are stored with a
                              named error and never reach ``tasks``.
* ``swarm_messages``        — conversation turns (``kind = 'chat'``) and
                              addressed peer messages (``kind = 'peer'``)
                              with durable IDs, delivery and acknowledgement.
* ``swarm_task_context``    — per-task project/role/verification context and
                              the base SHA recorded when the revision was
                              applied. One row per swarm-owned ``tasks`` row.
* ``swarm_task_attempts``   — one row per execution attempt: worktree, branch,
                              agent process group, base/head SHA, structured
                              result, verification evidence, review, cost.

Revision ID: 029_swarm_runtime
Revises: 028_webauthn_user_handles
Create Date: 2026-09-29
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "029_swarm_runtime"
down_revision: str | None = "028_webauthn_user_handles"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


_UPGRADE_SQL: tuple[str, ...] = (
    """
    CREATE TABLE swarm_sessions (
        id                 TEXT PRIMARY KEY,
        title              TEXT NOT NULL DEFAULT '',
        registry_path      TEXT NOT NULL,
        plan_id            TEXT REFERENCES plans (id) ON DELETE SET NULL,
        applied_revision   INTEGER,
        status             TEXT NOT NULL DEFAULT 'chatting',
        coordinator_id     TEXT,
        coordinator_host   TEXT,
        coordinator_pid    INTEGER,
        lease_expires_at   TIMESTAMPTZ,
        stop_requested     BOOLEAN NOT NULL DEFAULT FALSE,
        created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT ck_swarm_sessions_status CHECK (
            status IN ('chatting', 'running', 'stopping', 'stopped', 'finished')
        )
    )
    """,
    """
    CREATE TABLE swarm_plan_revisions (
        session_id         TEXT NOT NULL REFERENCES swarm_sessions (id) ON DELETE CASCADE,
        revision           INTEGER NOT NULL,
        status             TEXT NOT NULL,
        source             TEXT NOT NULL,
        plan               JSONB,
        raw_text           TEXT NOT NULL DEFAULT '',
        error              TEXT,
        registry_snapshot  JSONB,
        created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        applied_at         TIMESTAMPTZ,
        PRIMARY KEY (session_id, revision),
        CONSTRAINT ck_swarm_plan_revisions_status CHECK (
            status IN ('proposed', 'invalid', 'applied', 'superseded')
        )
    )
    """,
    """
    CREATE TABLE swarm_messages (
        id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        session_id   TEXT NOT NULL REFERENCES swarm_sessions (id) ON DELETE CASCADE,
        kind         TEXT NOT NULL,
        sender       TEXT NOT NULL,
        recipient    TEXT,
        task_ref     TEXT,
        body         TEXT NOT NULL,
        created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        delivered_at TIMESTAMPTZ,
        acked_at     TIMESTAMPTZ,
        CONSTRAINT ck_swarm_messages_kind CHECK (kind IN ('chat', 'peer')),
        CONSTRAINT ck_swarm_messages_peer_recipient CHECK (kind = 'chat' OR recipient IS NOT NULL)
    )
    """,
    "CREATE INDEX ix_swarm_messages_inbox ON swarm_messages (session_id, recipient, acked_at)",
    """
    CREATE TABLE swarm_task_context (
        task_id        TEXT PRIMARY KEY REFERENCES tasks (id) ON DELETE CASCADE,
        session_id     TEXT NOT NULL REFERENCES swarm_sessions (id) ON DELETE CASCADE,
        revision       INTEGER NOT NULL,
        local_id       TEXT NOT NULL,
        project_id     TEXT NOT NULL,
        role           TEXT NOT NULL,
        depends_on     JSONB NOT NULL DEFAULT '[]'::jsonb,
        verification   JSONB NOT NULL DEFAULT '[]'::jsonb,
        base_ref       TEXT NOT NULL,
        base_sha       TEXT NOT NULL,
        max_attempts   INTEGER NOT NULL,
        outcome        TEXT,
        blocker        TEXT,
        UNIQUE (session_id, revision, local_id)
    )
    """,
    """
    CREATE TABLE swarm_task_attempts (
        id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        task_id        TEXT NOT NULL REFERENCES tasks (id) ON DELETE CASCADE,
        attempt        INTEGER NOT NULL,
        status         TEXT NOT NULL DEFAULT 'running',
        coordinator_id TEXT NOT NULL,
        host           TEXT NOT NULL,
        agent_pgid     INTEGER,
        worktree_path  TEXT,
        branch         TEXT,
        log_dir        TEXT,
        base_sha       TEXT,
        head_sha       TEXT,
        result         JSONB,
        verification   JSONB,
        review         JSONB,
        error          TEXT,
        cost_usd       NUMERIC(12, 6) NOT NULL DEFAULT 0,
        started_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        finished_at    TIMESTAMPTZ,
        UNIQUE (task_id, attempt),
        CONSTRAINT ck_swarm_task_attempts_status CHECK (
            status IN ('running', 'accepted', 'failed', 'cancelled', 'abandoned')
        )
    )
    """,
)

_DOWNGRADE_SQL: tuple[str, ...] = (
    "DROP TABLE IF EXISTS swarm_task_attempts",
    "DROP TABLE IF EXISTS swarm_task_context",
    "DROP TABLE IF EXISTS swarm_messages",
    "DROP TABLE IF EXISTS swarm_plan_revisions",
    "DROP TABLE IF EXISTS swarm_sessions",
)


def upgrade() -> None:
    for statement in _UPGRADE_SQL:
        op.execute(statement)


def downgrade() -> None:
    for statement in _DOWNGRADE_SQL:
        op.execute(statement)
