"""Durable call reservations and nullable costs for local swarm engines."""

from alembic import op

revision = "030_swarm_agent_calls"
down_revision = "029_swarm_runtime"
branch_labels = None
depends_on = None


def upgrade():
    op.execute("ALTER TABLE swarm_task_attempts ALTER COLUMN cost_usd DROP NOT NULL")
    op.execute("""
        CREATE TABLE swarm_agent_calls (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            session_id TEXT NOT NULL REFERENCES swarm_sessions(id) ON DELETE CASCADE,
            engine TEXT NOT NULL,
            mode TEXT NOT NULL,
            task_id TEXT REFERENCES tasks(id) ON DELETE SET NULL,
            prompt_chars INTEGER NOT NULL CHECK (prompt_chars >= 0),
            usage JSONB,
            cost_usd NUMERIC(12,6),
            error TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            finished_at TIMESTAMPTZ
        )
    """)
    op.execute("CREATE INDEX ix_swarm_agent_calls_session ON swarm_agent_calls(session_id)")


def downgrade():
    op.execute("DROP TABLE swarm_agent_calls")
    op.execute("UPDATE swarm_task_attempts SET cost_usd=0 WHERE cost_usd IS NULL")
    op.execute("ALTER TABLE swarm_task_attempts ALTER COLUMN cost_usd SET NOT NULL")
