"""Durable product chat and feature specifications."""

from alembic import op

revision = "031_product_swarm"
down_revision = "030_swarm_agent_calls"
branch_labels = None
depends_on = None


def upgrade():
    op.execute(
        "CREATE TABLE swarm_products (id TEXT PRIMARY KEY, name TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())"
    )
    op.execute(
        "CREATE TABLE swarm_product_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, product_id TEXT NOT NULL REFERENCES swarm_products(id) ON DELETE CASCADE, sender TEXT NOT NULL, body TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())"
    )
    op.execute("""CREATE TABLE swarm_product_features (id TEXT PRIMARY KEY, product_id TEXT NOT NULL REFERENCES swarm_products(id) ON DELETE CASCADE,
        title TEXT NOT NULL, intent TEXT NOT NULL, session_id TEXT NOT NULL REFERENCES swarm_sessions(id), status TEXT NOT NULL DEFAULT 'draft',
        revision INTEGER NOT NULL DEFAULT 0, spec JSONB, approval_digest TEXT, approved_digest TEXT, budget JSONB NOT NULL DEFAULT '{}'::jsonb,
        profiles JSONB NOT NULL DEFAULT '{}'::jsonb, base_shas JSONB NOT NULL DEFAULT '{}'::jsonb, blocker TEXT, plan_revision INTEGER,
        registry_hash TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT ck_swarm_product_feature_status CHECK (status IN ('draft','specifying','planned','approved','running','blocked','review','mr_ready')))""")
    op.execute(
        "CREATE TABLE swarm_product_specs (feature_id TEXT NOT NULL REFERENCES swarm_product_features(id) ON DELETE CASCADE, revision INTEGER NOT NULL, body JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), PRIMARY KEY(feature_id, revision))"
    )


def downgrade():
    op.execute("DROP TABLE IF EXISTS swarm_product_specs")
    op.execute("DROP TABLE IF EXISTS swarm_product_features")
    op.execute("DROP TABLE IF EXISTS swarm_product_messages")
    op.execute("DROP TABLE IF EXISTS swarm_products")
