"""Durable global model-call admission rows.

Rows with ``released_at IS NULL`` are active reservations. They are
deliberately not reclaimed by this migration or by the admission wrapper:
unknown process death must fail closed rather than risk exceeding capacity.
"""

from alembic import op

revision = "032_model_admission"
down_revision = "031_product_swarm"
branch_labels = None
depends_on = None


def upgrade():
    op.execute(
        """
        CREATE TABLE swarm_model_admissions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            advisory_key BIGINT NOT NULL,
            owner_host TEXT NOT NULL,
            owner_pid INTEGER NOT NULL,
            owner_started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            acquired_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            released_at TIMESTAMPTZ
        )
        """
    )
    op.execute(
        "CREATE INDEX ix_swarm_model_admissions_active "
        "ON swarm_model_admissions (released_at) WHERE released_at IS NULL"
    )


def downgrade():
    op.execute("DROP TABLE IF EXISTS swarm_model_admissions")
