"""Immutable learning task proposals and append-only lifecycle events."""

from alembic import op

revision = "039_learning_proposals"
down_revision = "038_learning_messages"
branch_labels = None
depends_on = None


def upgrade():
    op.execute("""CREATE TABLE swarm_learning_proposals (
        id TEXT PRIMARY KEY,
        product_id TEXT NOT NULL REFERENCES swarm_products(id) ON DELETE CASCADE,
        origin_feature_id TEXT NOT NULL,
        origin_task_id TEXT,
        target_project TEXT NOT NULL,
        target_module TEXT NOT NULL,
        evidence_refs JSONB NOT NULL,
        outcome TEXT NOT NULL,
        contract_impact TEXT NOT NULL,
        acceptance JSONB NOT NULL,
        dependencies JSONB NOT NULL,
        resource_class TEXT NOT NULL,
        fingerprint TEXT NOT NULL,
        status TEXT NOT NULL CHECK (status IN ('proposed','triaged','awaiting_approval','eligible','queued','running','verified','blocked','rejected','cancelled')),
        actor_id TEXT NOT NULL,
        actor_host TEXT NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        UNIQUE (product_id, target_project, target_module, fingerprint)
    )""")
    op.execute("""CREATE TABLE swarm_learning_proposal_events (
        event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        proposal_id TEXT NOT NULL REFERENCES swarm_learning_proposals(id) ON DELETE CASCADE,
        from_state TEXT,
        to_state TEXT NOT NULL CHECK (to_state IN ('proposed','triaged','awaiting_approval','eligible','queued','running','verified','blocked','rejected','cancelled')),
        actor_id TEXT NOT NULL,
        actor_host TEXT NOT NULL,
        reason TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )""")
    op.execute(
        "CREATE INDEX swarm_learning_proposal_events_idx ON swarm_learning_proposal_events (proposal_id, event_id)"
    )
    op.execute("""CREATE FUNCTION swarm_learning_proposals_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
        IF NEW.status <> OLD.status AND NOT (
            (OLD.status = 'proposed' AND NEW.status IN ('triaged','rejected','cancelled')) OR
            (OLD.status = 'triaged' AND NEW.status IN ('awaiting_approval','eligible','rejected','cancelled')) OR
            (OLD.status = 'awaiting_approval' AND NEW.status IN ('eligible','rejected','cancelled')) OR
            (OLD.status = 'eligible' AND NEW.status IN ('queued','blocked','rejected','cancelled')) OR
            (OLD.status = 'queued' AND NEW.status IN ('running','blocked','cancelled')) OR
            (OLD.status = 'running' AND NEW.status IN ('verified','blocked','cancelled')) OR
            (OLD.status = 'blocked' AND NEW.status IN ('triaged','cancelled'))
        ) THEN
            RAISE EXCEPTION 'illegal proposal transition';
        END IF;
        IF NEW.id <> OLD.id OR NEW.product_id <> OLD.product_id OR NEW.origin_feature_id <> OLD.origin_feature_id
           OR NEW.origin_task_id IS DISTINCT FROM OLD.origin_task_id OR NEW.target_project <> OLD.target_project
           OR NEW.target_module <> OLD.target_module OR NEW.evidence_refs <> OLD.evidence_refs
           OR NEW.outcome <> OLD.outcome OR NEW.contract_impact <> OLD.contract_impact
           OR NEW.acceptance <> OLD.acceptance OR NEW.dependencies <> OLD.dependencies
           OR NEW.resource_class <> OLD.resource_class OR NEW.fingerprint <> OLD.fingerprint
           OR NEW.actor_id <> OLD.actor_id OR NEW.actor_host <> OLD.actor_host
           OR NEW.created_at <> OLD.created_at THEN
            RAISE EXCEPTION 'proposal content is immutable';
        END IF;
        NEW.updated_at = NOW();
        RETURN NEW;
    END $$""")
    op.execute("""CREATE TRIGGER swarm_learning_proposals_immutable_trg
        BEFORE UPDATE ON swarm_learning_proposals FOR EACH ROW EXECUTE FUNCTION swarm_learning_proposals_immutable()""")
    op.execute("""CREATE FUNCTION swarm_learning_proposal_events_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN RAISE EXCEPTION 'proposal event history is append-only'; END $$""")
    op.execute("""CREATE TRIGGER swarm_learning_proposal_events_append_only_trg
        BEFORE UPDATE OR DELETE ON swarm_learning_proposal_events FOR EACH ROW EXECUTE FUNCTION swarm_learning_proposal_events_append_only()""")
    op.execute("""CREATE FUNCTION swarm_learning_proposal_event_consistent() RETURNS trigger LANGUAGE plpgsql AS $$
    DECLARE
        current_status TEXT;
        prior_state TEXT;
        event_count BIGINT;
    BEGIN
        SELECT status INTO current_status FROM swarm_learning_proposals WHERE id=NEW.proposal_id FOR UPDATE;
        IF current_status IS NULL THEN
            RAISE EXCEPTION 'inconsistent proposal event';
        END IF;
        SELECT COUNT(*) INTO event_count
          FROM swarm_learning_proposal_events WHERE proposal_id=NEW.proposal_id;
        SELECT to_state INTO prior_state
          FROM swarm_learning_proposal_events
          WHERE proposal_id=NEW.proposal_id ORDER BY event_id DESC LIMIT 1;
        IF NEW.from_state IS NULL THEN
            IF event_count <> 0 OR NEW.to_state <> 'proposed' OR current_status <> 'proposed' THEN
                RAISE EXCEPTION 'inconsistent proposal event';
            END IF;
        ELSIF event_count = 0 OR prior_state IS DISTINCT FROM NEW.from_state
           OR current_status <> NEW.to_state
           OR NOT (
                (NEW.from_state = 'proposed' AND NEW.to_state IN ('triaged','rejected','cancelled')) OR
                (NEW.from_state = 'triaged' AND NEW.to_state IN ('awaiting_approval','eligible','rejected','cancelled')) OR
                (NEW.from_state = 'awaiting_approval' AND NEW.to_state IN ('eligible','rejected','cancelled')) OR
                (NEW.from_state = 'eligible' AND NEW.to_state IN ('queued','blocked','rejected','cancelled')) OR
                (NEW.from_state = 'queued' AND NEW.to_state IN ('running','blocked','cancelled')) OR
                (NEW.from_state = 'running' AND NEW.to_state IN ('verified','blocked','cancelled')) OR
                (NEW.from_state = 'blocked' AND NEW.to_state IN ('triaged','cancelled'))
           ) THEN
            RAISE EXCEPTION 'inconsistent proposal event';
        END IF;
        RETURN NEW;
    END $$""")
    op.execute("""CREATE TRIGGER swarm_learning_proposal_event_consistent_trg
        BEFORE INSERT ON swarm_learning_proposal_events FOR EACH ROW EXECUTE FUNCTION swarm_learning_proposal_event_consistent()""")
    op.execute("""CREATE FUNCTION swarm_learning_proposal_status_event_complete() RETURNS trigger LANGUAGE plpgsql AS $$
    DECLARE
        current_status TEXT;
        last_state TEXT;
    BEGIN
        SELECT status INTO current_status FROM swarm_learning_proposals WHERE id=NEW.id;
        SELECT to_state INTO last_state
          FROM swarm_learning_proposal_events
          WHERE proposal_id=NEW.id ORDER BY event_id DESC LIMIT 1;
        IF last_state IS DISTINCT FROM current_status THEN
            RAISE EXCEPTION 'missing proposal lifecycle event';
        END IF;
        RETURN NEW;
    END $$""")
    op.execute("""CREATE CONSTRAINT TRIGGER swarm_learning_proposal_status_event_complete_trg
        AFTER UPDATE OF status ON swarm_learning_proposals
        DEFERRABLE INITIALLY DEFERRED FOR EACH ROW
        EXECUTE FUNCTION swarm_learning_proposal_status_event_complete()""")


def downgrade():
    op.execute("DROP TRIGGER IF EXISTS swarm_learning_proposal_status_event_complete_trg ON swarm_learning_proposals")
    op.execute("DROP FUNCTION IF EXISTS swarm_learning_proposal_status_event_complete()")
    op.execute("DROP TRIGGER IF EXISTS swarm_learning_proposal_event_consistent_trg ON swarm_learning_proposal_events")
    op.execute("DROP FUNCTION IF EXISTS swarm_learning_proposal_event_consistent()")
    op.execute(
        "DROP TRIGGER IF EXISTS swarm_learning_proposal_events_append_only_trg ON swarm_learning_proposal_events"
    )
    op.execute("DROP FUNCTION IF EXISTS swarm_learning_proposal_events_append_only()")
    op.execute("DROP TRIGGER IF EXISTS swarm_learning_proposals_immutable_trg ON swarm_learning_proposals")
    op.execute("DROP FUNCTION IF EXISTS swarm_learning_proposals_immutable()")
    op.execute("DROP TABLE IF EXISTS swarm_learning_proposal_events")
    op.execute("DROP TABLE IF EXISTS swarm_learning_proposals")
