"""Disabled-by-default daily learning schedules, runs and atomic call budgets."""

from alembic import op

revision = "040_learning_runs"
down_revision = "039_learning_proposals"
branch_labels = None
depends_on = None


def upgrade():
    op.execute(
        """
        CREATE TABLE swarm_learning_schedules (
            product_id TEXT NOT NULL REFERENCES swarm_products(id) ON DELETE CASCADE,
            id TEXT NOT NULL,
            timezone TEXT NOT NULL,
            run_window TEXT NOT NULL,
            enabled BOOLEAN NOT NULL DEFAULT FALSE,
            model_profiles JSONB NOT NULL DEFAULT '{}'::jsonb,
            limits JSONB NOT NULL DEFAULT '{}'::jsonb,
            source_policy JSONB NOT NULL DEFAULT '{}'::jsonb,
            retention_policy JSONB NOT NULL DEFAULT '{}'::jsonb,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            PRIMARY KEY (product_id, id),
            CONSTRAINT ck_learning_schedule_window CHECK (run_window ~ '^[0-2][0-9]:[0-5][0-9]-[0-2][0-9]:[0-5][0-9]$')
        )
        """
    )
    op.execute(
        """
        CREATE TABLE swarm_learning_runs (
            id TEXT PRIMARY KEY,
            product_id TEXT NOT NULL,
            schedule_id TEXT NOT NULL,
            window_date DATE NOT NULL,
            window_key TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'running',
            stop_requested BOOLEAN NOT NULL DEFAULT FALSE,
            lease_expires_at TIMESTAMPTZ NOT NULL,
            claimed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            finished_at TIMESTAMPTZ,
            blocker TEXT,
            max_calls INTEGER NOT NULL CHECK (max_calls > 0),
            max_seconds INTEGER NOT NULL CHECK (max_seconds > 0),
            max_documents INTEGER NOT NULL CHECK (max_documents > 0),
            max_bytes BIGINT NOT NULL CHECK (max_bytes > 0),
            call_count INTEGER NOT NULL DEFAULT 0 CHECK (call_count >= 0),
            reserved_seconds INTEGER NOT NULL DEFAULT 0 CHECK (reserved_seconds >= 0),
            document_count INTEGER NOT NULL DEFAULT 0 CHECK (document_count >= 0),
            document_bytes BIGINT NOT NULL DEFAULT 0 CHECK (document_bytes >= 0),
            FOREIGN KEY (product_id, schedule_id)
                REFERENCES swarm_learning_schedules(product_id, id) ON DELETE CASCADE,
            UNIQUE (product_id, id),
            CONSTRAINT ck_learning_run_status CHECK (
                status IN ('running','completed','blocked','skipped','partial_failure','stopped')
            ),
            CONSTRAINT uq_learning_run_window UNIQUE (product_id, schedule_id, window_date, window_key)
        )
        """
    )
    op.execute(
        """
        CREATE TABLE swarm_learning_run_calls (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            product_id TEXT NOT NULL,
            run_id TEXT NOT NULL,
            admission_id BIGINT NOT NULL REFERENCES swarm_model_admissions(id),
            reserved_seconds INTEGER NOT NULL CHECK (reserved_seconds > 0),
            status TEXT NOT NULL DEFAULT 'reserved',
            outcome TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            finished_at TIMESTAMPTZ,
            CONSTRAINT ck_learning_call_status CHECK (status IN ('reserved','finished')),
            CONSTRAINT ck_learning_call_outcome CHECK (
                outcome IS NULL OR outcome IN ('completed','failed','cancelled','timed_out')
            ),
            FOREIGN KEY (product_id, run_id) REFERENCES swarm_learning_runs(product_id, id) ON DELETE CASCADE
        )
        """
    )
    op.execute("CREATE INDEX ix_learning_runs_due ON swarm_learning_runs (product_id, schedule_id, window_date)")
    op.execute("CREATE INDEX ix_learning_run_calls_run ON swarm_learning_run_calls (product_id, run_id)")


def downgrade():
    op.execute("DROP TABLE IF EXISTS swarm_learning_run_calls")
    op.execute("DROP TABLE IF EXISTS swarm_learning_runs")
    op.execute("DROP TABLE IF EXISTS swarm_learning_schedules")
