"""Durable product change-set state and immutable audit/effect receipts."""

from alembic import op

revision = "041_product_change_sets"
down_revision = "040_learning_runs"
branch_labels = None
depends_on = None


def upgrade():
    op.execute("""
        CREATE TABLE product_change_sets (
            id TEXT PRIMARY KEY, product_id TEXT NOT NULL, goal TEXT NOT NULL CHECK (length(trim(goal)) > 0),
            acceptance_criteria JSONB NOT NULL CHECK (jsonb_typeof(acceptance_criteria)='array' AND jsonb_array_length(acceptance_criteria)>0),
            registry_snapshot JSONB NOT NULL CHECK (jsonb_typeof(registry_snapshot)='object'),
            registry_digest TEXT NOT NULL CHECK (registry_digest ~ '^[0-9a-f]{64}$'),
            approval_digest TEXT CHECK (approval_digest ~ '^[0-9a-f]{64}$'),
            base_shas JSONB NOT NULL CHECK (jsonb_typeof(base_shas)='object'),
            dependencies JSONB NOT NULL CHECK (jsonb_typeof(dependencies)='object'),
            status TEXT NOT NULL DEFAULT 'DRAFT' CHECK (status IN (
                'DRAFT','PLANNED','EXECUTING','VERIFYING_REPOS','VERIFYING_INTEGRATION','READY_TO_MERGE',
                'MERGING','MERGED','DEPLOYING_STAGE','ACCEPTING_STAGE','DONE','BLOCKED','FAILED','PARTIAL_MERGE',
                'ROLLING_BACK','ROLLED_BACK','ROLLBACK_FAILED','MANUAL_DECISION_REQUIRED')),
            version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0), resume_status TEXT,
            last_evidence JSONB NOT NULL CHECK (jsonb_typeof(last_evidence)='object'),
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            CONSTRAINT ck_change_set_done_evidence CHECK (status <> 'DONE' OR COALESCE(
                last_evidence @> '{"kind":"stage_acceptance","outcome":"PASSED","environment":"stage"}'::jsonb, FALSE))
        )
    """)
    op.execute("""
        CREATE TABLE repo_changes (
            change_id TEXT NOT NULL REFERENCES product_change_sets(id) ON DELETE RESTRICT,
            repo_id TEXT NOT NULL, base_sha TEXT NOT NULL CHECK (base_sha ~ '^([0-9a-f]{40}|[0-9a-f]{64})$'),
            status TEXT NOT NULL DEFAULT 'PLANNED' CHECK (status IN (
                'PLANNED','WORKTREE_READY','IMPLEMENTING','LOCAL_VERIFIED','MR_OPEN','PIPELINE_GREEN',
                'READY_TO_MERGE','MERGED','ARTIFACT_READY','NOT_IMPACTED','BLOCKED','FAILED',
                'REVERT_OPEN','REVERTED','ROLLBACK_FAILED')),
            version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0), mandatory BOOLEAN NOT NULL DEFAULT TRUE,
            last_evidence JSONB NOT NULL CHECK (jsonb_typeof(last_evidence)='object'), resume_status TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            PRIMARY KEY (change_id, repo_id)
        )
    """)
    op.execute("""
        CREATE TABLE change_set_events (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            change_id TEXT NOT NULL REFERENCES product_change_sets(id) ON DELETE RESTRICT,
            repo_id TEXT, entity_version INTEGER NOT NULL CHECK (entity_version > 0),
            from_status TEXT, to_status TEXT NOT NULL,
            evidence JSONB NOT NULL CHECK (jsonb_typeof(evidence)='object'),
            idempotency_key TEXT NOT NULL UNIQUE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            FOREIGN KEY (change_id, repo_id) REFERENCES repo_changes(change_id, repo_id) ON DELETE RESTRICT
        )
    """)
    op.execute(
        "CREATE UNIQUE INDEX uq_change_set_event_version ON change_set_events(change_id, entity_version) WHERE repo_id IS NULL"
    )
    op.execute(
        "CREATE UNIQUE INDEX uq_repo_change_event_version ON change_set_events(change_id, repo_id, entity_version) WHERE repo_id IS NOT NULL"
    )
    op.execute("""
        CREATE TABLE external_effect_receipts (
            effect_key TEXT PRIMARY KEY, change_id TEXT NOT NULL REFERENCES product_change_sets(id) ON DELETE RESTRICT,
            repo_id TEXT, operation TEXT NOT NULL CHECK (length(trim(operation)) > 0),
            request_digest TEXT NOT NULL CHECK (request_digest ~ '^[0-9a-f]{64}$'),
            evidence JSONB NOT NULL CHECK (jsonb_typeof(evidence)='object'),
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            FOREIGN KEY (change_id, repo_id) REFERENCES repo_changes(change_id, repo_id) ON DELETE RESTRICT
        )
    """)
    op.execute("""
        CREATE FUNCTION valid_change_set_evidence(value JSONB) RETURNS BOOLEAN LANGUAGE SQL IMMUTABLE AS $$
        SELECT COALESCE(
            jsonb_typeof(value)='object' AND jsonb_typeof(value->'kind')='string'
            AND length(trim(value->>'kind'))>0 AND value->>'outcome' IN ('PASSED','FAILED','UNAVAILABLE')
            AND (jsonb_typeof(value->'details')='object')
            AND CASE
                WHEN NOT (value ? 'command') THEN TRUE
                WHEN jsonb_typeof(value->'command')='array' THEN NOT EXISTS (
                    SELECT 1 FROM jsonb_array_elements(value->'command') AS args(argument)
                    WHERE jsonb_typeof(args.argument) IS DISTINCT FROM 'string'
                       OR length(args.argument #>> '{}')=0
                )
                ELSE FALSE
            END
            AND ((jsonb_typeof(value->'absence')='string' AND length(trim(value->>'absence'))>0
                  AND value->>'outcome'<>'PASSED')
                OR ((value->>'sha') ~ '^([0-9a-f]{40}|[0-9a-f]{64})$'
                    AND ((jsonb_typeof(value->'job_id')='string' AND length(trim(value->>'job_id'))>0)
                         OR (CASE WHEN jsonb_typeof(value->'command')='array'
                             THEN jsonb_array_length(value->'command')>0 ELSE FALSE END
                             AND jsonb_typeof(value->'exit_code')='number'))))
            AND (value->>'outcome'<>'UNAVAILABLE' OR
                 (jsonb_typeof(value->'absence')='string' AND length(trim(value->>'absence'))>0))
            AND (value->>'outcome'<>'PASSED' OR
                 ((value->>'absence') IS NULL AND COALESCE(value->>'exit_code','0')='0')),
            FALSE)
        $$
    """)
    for table, column in (
        ("product_change_sets", "last_evidence"),
        ("repo_changes", "last_evidence"),
        ("change_set_events", "evidence"),
        ("external_effect_receipts", "evidence"),
    ):
        op.execute(
            f"ALTER TABLE {table} ADD CONSTRAINT ck_{table}_valid_evidence CHECK (valid_change_set_evidence({column}))"
        )
    op.execute("""
        CREATE FUNCTION guard_change_set_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN RAISE EXCEPTION 'change_set_evidence_is_append_only'; END; $$
    """)
    for table in ("change_set_events", "external_effect_receipts"):
        op.execute(
            f"CREATE TRIGGER {table}_immutable BEFORE UPDATE OR DELETE ON {table} FOR EACH ROW EXECUTE FUNCTION guard_change_set_append_only()"
        )
        op.execute(
            f"CREATE TRIGGER {table}_no_truncate BEFORE TRUNCATE ON {table} FOR EACH STATEMENT EXECUTE FUNCTION guard_change_set_append_only()"
        )
    op.execute("""
        CREATE FUNCTION guard_change_set_definition() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF ROW(NEW.id,NEW.product_id,NEW.goal,NEW.acceptance_criteria,NEW.registry_snapshot,
                NEW.registry_digest,NEW.base_shas,NEW.dependencies,NEW.created_at)
                IS DISTINCT FROM ROW(OLD.id,OLD.product_id,OLD.goal,OLD.acceptance_criteria,OLD.registry_snapshot,
                OLD.registry_digest,OLD.base_shas,OLD.dependencies,OLD.created_at) THEN
                RAISE EXCEPTION 'change_set_definition_is_immutable';
            END IF;
            IF NEW.approval_digest IS DISTINCT FROM OLD.approval_digest AND NOT
                (OLD.approval_digest IS NULL AND OLD.status='PLANNED' AND NEW.status='EXECUTING') THEN
                RAISE EXCEPTION 'change_set_approval_is_immutable';
            END IF;
            IF NEW.version <> OLD.version + 1 THEN RAISE EXCEPTION 'change_set_version_must_advance'; END IF;
            RETURN NEW;
        END; $$
    """)
    op.execute(
        "CREATE TRIGGER product_change_sets_definition BEFORE UPDATE ON product_change_sets FOR EACH ROW EXECUTE FUNCTION guard_change_set_definition()"
    )
    op.execute("""
        CREATE FUNCTION guard_repo_change_definition() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF ROW(NEW.change_id,NEW.repo_id,NEW.base_sha,NEW.created_at)
                IS DISTINCT FROM ROW(OLD.change_id,OLD.repo_id,OLD.base_sha,OLD.created_at) THEN
                RAISE EXCEPTION 'repo_change_definition_is_immutable';
            END IF;
            IF NEW.mandatory IS DISTINCT FROM OLD.mandatory AND NOT
                (OLD.mandatory AND NOT NEW.mandatory AND OLD.status='PLANNED' AND NEW.status='NOT_IMPACTED') THEN
                RAISE EXCEPTION 'repo_change_impact_transition_required';
            END IF;
            IF NEW.version <> OLD.version + 1 THEN RAISE EXCEPTION 'repo_change_version_must_advance'; END IF;
            RETURN NEW;
        END; $$
    """)
    op.execute(
        "CREATE TRIGGER repo_changes_definition BEFORE UPDATE ON repo_changes FOR EACH ROW EXECUTE FUNCTION guard_repo_change_definition()"
    )


def downgrade():
    for table in ("external_effect_receipts", "change_set_events", "repo_changes", "product_change_sets"):
        op.execute(f"DROP TABLE {table}")
    for function in ("guard_repo_change_definition", "guard_change_set_definition", "guard_change_set_append_only"):
        op.execute(f"DROP FUNCTION {function}()")
    op.execute("DROP FUNCTION valid_change_set_evidence(JSONB)")
