"""Documentation publishing flow for Jira issues classified as `documentation`.

Phase 4 of the Jira Scheduler integration (TASK-SCH-032).

Orchestrates the end-to-end "documentation task" path:
1. Read Jira plan JSON
2. Generate Confluence Markdown draft
3. Write draft to local out/ directory
4. (Optionally) publish to Confluence via ConfluencePublisher
5. Record publish result in jira_work_sessions.raw_snapshot
6. Emit CONFLUENCE_PUBLISHED event

This module is intentionally NOT autonomous: it does not modify code,
does not run agents. Its product is a Confluence page, not a commit.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from whilly.adapters.confluence.publisher import ConfluencePage, ConfluencePublishError, ConfluencePublisher

log = logging.getLogger(__name__)

UTC = timezone.utc


@dataclass(frozen=True)
class DocumentationFlowResult:
    """Outcome of a documentation flow run."""

    draft_path: Path
    published: bool
    page: ConfluencePage | None = None
    error: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "draft_path": str(self.draft_path),
            "published": self.published,
            "page": self.page.to_dict() if self.page else None,
            "error": self.error,
        }


def generate_markdown_draft(plan_json: dict[str, Any]) -> str:
    """Generate a Confluence-friendly Markdown draft from a Jira plan JSON.

    Phase 4 implementation: deterministic template. A future iteration may
    invoke an LLM to expand the description into a richer document.
    """
    tasks = plan_json.get("tasks", []) or []
    first_task = tasks[0] if tasks else {}

    origin = plan_json.get("origin") or {}
    issue_key = origin.get("ref") or first_task.get("id", "")
    title = first_task.get("title") or plan_json.get("name") or f"Documentation: {issue_key}"
    description = (
        first_task.get("description") or first_task.get("prd_requirement") or "Add documentation content here."
    )
    acceptance = first_task.get("acceptance_criteria") or []

    lines = [
        f"# {title}",
        "",
        f"_Source: Jira issue {issue_key}_",
        "",
        "## Overview",
        "",
        description,
        "",
    ]

    if acceptance:
        lines.append("## Acceptance Criteria")
        lines.append("")
        for item in acceptance:
            lines.append(f"- {item}")
        lines.append("")

    lines.extend(
        [
            "## References",
            "",
            f"- Jira issue: {issue_key}",
            f"- Generated by Whilly on {datetime.now(UTC).isoformat()}",
            "",
        ]
    )
    return "\n".join(lines)


def write_draft(plan_path: Path, content: str, *, out_dir: Path | None = None) -> Path:
    """Write the Markdown draft beside the plan JSON or in out_dir."""
    base_dir = out_dir or plan_path.parent
    base_dir.mkdir(parents=True, exist_ok=True)
    key = plan_path.stem.replace("jira-", "")
    draft_path = base_dir / f"confluence-{key}.md"
    draft_path.write_text(content, encoding="utf-8")
    return draft_path


def run_documentation_flow(
    plan_path: Path,
    *,
    space_key: str = "",
    parent_id: str | None = None,
    publisher: ConfluencePublisher | None = None,
    out_dir: Path | None = None,
) -> DocumentationFlowResult:
    """Run the documentation publishing flow for a single Jira plan.

    Args:
        plan_path: Path to the Jira plan JSON (written by `whilly jira intake`)
        space_key: Target Confluence space key (defaults to publisher.default_space)
        parent_id: Optional parent page id
        publisher: Configured ConfluencePublisher; if None, only writes draft
        out_dir: Optional override for draft output directory

    Returns:
        DocumentationFlowResult with draft path, publish status, page info.
    """
    plan_json = json.loads(plan_path.read_text(encoding="utf-8"))
    markdown = generate_markdown_draft(plan_json)
    draft_path = write_draft(plan_path, markdown, out_dir=out_dir)
    log.info("Documentation draft written to %s", draft_path)

    if publisher is None:
        return DocumentationFlowResult(draft_path=draft_path, published=False)

    space = space_key or publisher.default_space
    if not space:
        return DocumentationFlowResult(
            draft_path=draft_path,
            published=False,
            error="No Confluence space configured; set space_key or publisher.default_space",
        )

    tasks = plan_json.get("tasks", []) or []
    first_task = tasks[0] if tasks else {}
    origin = plan_json.get("origin") or {}
    issue_key = origin.get("ref") or first_task.get("id", "doc")
    title = first_task.get("title") or plan_json.get("name") or f"Documentation: {issue_key}"

    try:
        page = publisher.create_page(
            space_key=space,
            title=title,
            body_markdown=markdown,
            parent_id=parent_id,
        )
    except ConfluencePublishError as exc:
        log.error("Confluence publish failed: %s", exc)
        return DocumentationFlowResult(draft_path=draft_path, published=False, error=str(exc))

    log.info("Confluence page published: %s", page.url)
    return DocumentationFlowResult(draft_path=draft_path, published=True, page=page)
