"""Generate deterministic pytest scaffolds from QA release test plans."""

from __future__ import annotations

import pprint
import re
from pathlib import Path

from whilly.qa_release.models import QATestPlan

GENERATED_MARKER = "Generated by Whilly QA release"


def default_autotest_path(plan: QATestPlan, *, suite: str) -> Path:
    """Return the default relative pytest path inside a test monorepo."""

    slug = re.sub(r"[^A-Za-z0-9]+", "_", plan.release_key.lower()).strip("_") or "release"
    return Path("bigdata_tests") / suite / "tests" / f"test_{slug}_qa_release_plan.py"


def write_autotest_suite(
    plan: QATestPlan,
    *,
    repo_root: str | Path,
    suite: str,
    out_path: str | Path | None = None,
    force: bool = False,
) -> Path:
    """Create or update a generated pytest contract suite for ``plan``."""

    root = Path(repo_root).expanduser().resolve()
    relative = Path(out_path) if out_path is not None else default_autotest_path(plan, suite=suite)
    target = relative if relative.is_absolute() else root / relative
    content = render_autotest_suite(plan)
    if target.exists() and not force and GENERATED_MARKER not in target.read_text(encoding="utf-8"):
        raise RuntimeError(f"refusing to overwrite non-generated test file: {target}")
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")
    return target


def render_autotest_suite(plan: QATestPlan) -> str:
    """Render a stable local pytest suite that pins release plan contracts."""

    payload = pprint.pformat(plan.to_dict(), width=120, sort_dicts=True)
    return f'''"""QA release contract tests for {plan.release_key}.

{GENERATED_MARKER}. Safe to regenerate from the QA test-plan JSON.
These checks are local metadata contracts; cluster-facing functional tests
should be added beside them as release requirements become concrete.
"""

from __future__ import annotations


QA_TEST_PLAN = {payload}


def test_release_plan_has_requirement_coverage():
    requirement_ids = {{requirement["id"] for requirement in QA_TEST_PLAN["requirements"]}}
    covered_ids = {{
        requirement_id
        for test_case in QA_TEST_PLAN["test_cases"]
        for requirement_id in test_case["source_requirement_ids"]
    }}

    assert requirement_ids
    assert requirement_ids <= covered_ids


def test_release_repository_scope_is_pinned():
    repo_hints = QA_TEST_PLAN["repo_hints"]

    assert repo_hints, "release must have at least one implementation or deployment repository hint"
    assert all(repo["provider"] for repo in repo_hints)
    assert all(repo["repo_full_name"] for repo in repo_hints)
    assert any(repo["ref"] for repo in repo_hints), "at least one repo hint must pin tag, branch, or commit"


def test_release_preconditions_include_stage_and_test_monorepo():
    preconditions = "\\n".join(QA_TEST_PLAN["preconditions"]).lower()

    assert "stage" in preconditions
    assert "test monorepo" in preconditions


def test_release_test_plan_contains_regression_audit_case():
    kinds = {{test_case["kind"] for test_case in QA_TEST_PLAN["test_cases"]}}

    assert "regression" in kinds
'''
