#!/bin/sh
#
# Deterministic Claude CLI stub for the PRD-wizard integration tests
# (TASK-104a-5, paired with tests/integration/test_init_e2e.py).
#
# Why a separate stub from tests/fixtures/fake_claude.sh
# ------------------------------------------------------
# fake_claude.sh emits a worker-loop result envelope ({"result":
# "<promise>COMPLETE</promise>"}) — that's what the *worker* runner
# expects when it calls Claude on a single task. The PRD wizard's
# whilly.prd_generator._call_claude expects a *different* shape:
# bare stdout containing either a PRD markdown document or a JSON
# object describing a task plan, depending on which prompt was sent.
# Forcing one stub to do both jobs would muddy both responsibilities;
# splitting keeps each fixture readable.
#
# What it does
# ------------
# Looks at argv for the prompt that whilly.prd_generator built (the
# value passed after `-p`). Two distinguishing markers in the prompt
# tell us which response shape to emit:
#
#   * "Senior Product Manager"  → emit PRD markdown (generate_prd path)
#   * "Technical Project Manager" → emit tasks JSON (generate_tasks_dict path)
#
# Both markers are part of the system prompts hardcoded in
# whilly/prd_generator.py (search _PRD_SYSTEM_PROMPT /
# _TASKS_SYSTEM_PROMPT). If those strings ever drift, the stub has
# to update — but that's a feature: the test fails loudly when the
# wire shape changes, instead of silently passing on stale assumptions.
#
# The output payloads are intentionally tiny (one task in the plan,
# minimal PRD body) — the integration test cares about flow, not
# about a realistic plan size.
#
# Usage
# -----
#   chmod +x tests/fixtures/fake_claude_prd.sh
#   CLAUDE_BIN="$(pwd)/tests/fixtures/fake_claude_prd.sh" \
#     pytest tests/integration/test_init_e2e.py -v
#
# Exit codes mimic real Claude: 0 on success, 1 if neither marker is
# present (so an accidentally-pointing-at-this stub from a non-PRD
# call site fails loudly rather than emitting random output).

set -eu

# Concatenate all positional args into one string so we can pattern-match
# the prompt no matter where in argv it sits (claude --model X -p PROMPT
# puts the prompt at the end, but the stub stays robust to argv reorder).
prompt=""
for arg in "$@"; do
    prompt="$prompt $arg"
done

case "$prompt" in
    *"Technical Project Manager"*)
        # Tasks-payload path. Output is exactly what
        # whilly.prd_generator._build_tasks_payload expects to read
        # back: project name + at least one task with required fields
        # (id, status, priority, description). Defaults like
        # dependencies / key_files are filled in by the helper itself,
        # so we omit them here to keep the fixture compact.
        cat <<'TASKS_JSON'
{
  "project": "fake-init-project",
  "tasks": [
    {
      "id": "TASK-FAKE-001",
      "status": "pending",
      "priority": "critical",
      "description": "Synthetic task generated by fake_claude_prd.sh",
      "dependencies": [],
      "key_files": ["whilly/cli/init.py"],
      "acceptance_criteria": ["init e2e smoke passes"],
      "test_steps": ["pytest tests/integration/test_init_e2e.py -v"],
      "prd_requirement": "TASK-104a-5"
    }
  ]
}
TASKS_JSON
        exit 0
        ;;
    *"Senior Product Manager"*)
        # PRD-Markdown path. Doesn't have to be a "real" PRD — the
        # downstream parser just writes whatever stdout we emit to
        # docs/PRD-<slug>.md. We include enough structure to spot-
        # check in tests (an h1 heading and at least one section).
        cat <<'PRD_MD'
# PRD: fake init project

## Context

Synthetic PRD body emitted by tests/fixtures/fake_claude_prd.sh during
the TASK-104a-5 integration test. Not a real product spec.

## Goals

* Drive the v4 `whilly init` flow end-to-end against a real Postgres.
* Verify the headless-mode wiring: prd_generator → generate_tasks_dict →
  parse_plan_dict → cli.plan._async_import → DB.

## Non-goals

* Realistic PRD authoring; the wizard's prompts are not exercised here.
PRD_MD
        exit 0
        ;;
    *)
        echo "fake_claude_prd.sh: unknown prompt shape (no marker matched)" >&2
        exit 1
        ;;
esac
