"""Unit tests for whilly.sinks.gitlab_mr — GitLab MR opener."""

from __future__ import annotations

import subprocess
from pathlib import Path
from unittest.mock import patch

import pytest

from whilly.sinks.github_pr import PRResult
from whilly.sinks.gitlab_mr import (
    _branch_name,
    _extract_mr_number_from_url,
    _infer_remote_host,
    _mr_body,
    _mr_title,
    _resolve_gitlab_token,
    open_mr_for_task,
)
from whilly.task_manager import Task


# ── Fixtures ───────────────────────────────────────────────────────────────────


def _make_task(
    task_id: str = "TASK-001",
    description: str = "Implement the feature",
    acceptance_criteria: list[str] | None = None,
    test_steps: list[str] | None = None,
) -> Task:
    return Task(
        id=task_id,
        phase="build",
        category="feature",
        priority="high",
        description=description,
        status="done",
        acceptance_criteria=acceptance_criteria or ["AC-1", "AC-2"],
        test_steps=test_steps or ["Run pytest"],
    )


def _completed_process(returncode: int = 0, stdout: str = "", stderr: str = "") -> subprocess.CompletedProcess:
    return subprocess.CompletedProcess(args=[], returncode=returncode, stdout=stdout, stderr=stderr)


# ── _extract_mr_number_from_url ────────────────────────────────────────────────


@pytest.mark.parametrize(
    "url,expected",
    [
        ("https://gitlab.services.mts.ru/foo/bar/-/merge_requests/42", 42),
        ("https://gitlab.example.com/group/project/-/merge_requests/7", 7),
        ("not-a-url", None),
        ("", None),
    ],
)
def test_extract_mr_number_from_url(url: str, expected: int | None) -> None:
    assert _extract_mr_number_from_url(url) == expected


# ── _branch_name ──────────────────────────────────────────────────────────────


def test_branch_name_default_prefix() -> None:
    task = _make_task("TASK-42")
    assert _branch_name(task, "whilly") == "whilly/TASK-42"


def test_branch_name_sanitises_spaces() -> None:
    task = _make_task("my task id")
    result = _branch_name(task, "whilly")
    assert " " not in result
    assert result.startswith("whilly/")


# ── _mr_title ─────────────────────────────────────────────────────────────────


def test_mr_title_includes_task_id_and_truncated_description() -> None:
    task = _make_task("TASK-001", description="A" * 200)
    title = _mr_title(task)
    assert "TASK-001" in title
    assert len(title) <= 80  # generous upper bound; strict cap is prefix + 60


def test_mr_title_fallback_when_no_description() -> None:
    task = _make_task("TASK-001", description="")
    title = _mr_title(task)
    assert "TASK-001" in title


# ── _mr_body ──────────────────────────────────────────────────────────────────


def test_mr_body_contains_task_id_and_acceptance_criteria() -> None:
    task = _make_task("TASK-001", acceptance_criteria=["Must do X", "Must not do Y"])
    body = _mr_body(task)
    assert "TASK-001" in body
    assert "Must do X" in body
    assert "Must not do Y" in body
    assert "Generated by" in body


def test_mr_body_includes_test_steps() -> None:
    task = _make_task("TASK-001", test_steps=["Run pytest", "Check coverage"])
    body = _mr_body(task)
    assert "Run pytest" in body
    assert "Check coverage" in body


# ── _resolve_gitlab_token ─────────────────────────────────────────────────────


def test_resolve_gitlab_token_from_env_var() -> None:
    env = {"GITLAB_API_TOKEN": "secret-token"}
    assert _resolve_gitlab_token("gitlab.example.com", env=env) == "secret-token"


def test_resolve_gitlab_token_whilly_prefix_fallback() -> None:
    env = {"WHILLY_GITLAB_API_TOKEN": "whilly-token"}
    assert _resolve_gitlab_token("gitlab.example.com", env=env) == "whilly-token"


def test_resolve_gitlab_token_env_takes_priority_over_glab_cli() -> None:
    env = {"GITLAB_API_TOKEN": "env-token"}
    # glab should NOT be called when the env var is present
    with patch("subprocess.run") as mock_run:
        result = _resolve_gitlab_token("gitlab.example.com", env=env)
    assert result == "env-token"
    mock_run.assert_not_called()


def test_resolve_gitlab_token_glab_cli_fallback() -> None:
    env: dict[str, str] = {}
    glab_response = _completed_process(returncode=0, stdout="cli-token\n")
    with patch("subprocess.run", return_value=glab_response) as mock_run:
        result = _resolve_gitlab_token("gitlab.services.mts.ru", env=env)
    assert result == "cli-token"
    mock_run.assert_called_once()
    args = mock_run.call_args[0][0]
    assert "glab" in args
    assert "gitlab.services.mts.ru" in args


def test_resolve_gitlab_token_returns_none_when_both_missing() -> None:
    env: dict[str, str] = {}
    glab_response = _completed_process(returncode=1, stdout="", stderr="not configured")
    with patch("subprocess.run", return_value=glab_response):
        result = _resolve_gitlab_token("gitlab.example.com", env=env)
    assert result is None


def test_resolve_gitlab_token_returns_none_when_glab_raises() -> None:
    env: dict[str, str] = {}
    with patch("subprocess.run", side_effect=FileNotFoundError("glab not found")):
        result = _resolve_gitlab_token("gitlab.example.com", env=env)
    assert result is None


# ── _infer_remote_host ────────────────────────────────────────────────────────


def test_infer_remote_host_https_url(tmp_path: Path) -> None:
    git_response = _completed_process(returncode=0, stdout="https://gitlab.services.mts.ru/foo/bar.git\n")
    with patch("subprocess.run", return_value=git_response):
        host = _infer_remote_host(tmp_path)
    assert host == "gitlab.services.mts.ru"


def test_infer_remote_host_ssh_url(tmp_path: Path) -> None:
    git_response = _completed_process(returncode=0, stdout="git@gitlab.example.com:foo/bar.git\n")
    with patch("subprocess.run", return_value=git_response):
        host = _infer_remote_host(tmp_path)
    assert host == "gitlab.example.com"


def test_infer_remote_host_defaults_on_failure(tmp_path: Path) -> None:
    with patch("subprocess.run", side_effect=OSError("git not found")):
        host = _infer_remote_host(tmp_path)
    assert host == "gitlab.services.mts.ru"


# ── open_mr_for_task happy path ───────────────────────────────────────────────


def test_open_mr_for_task_happy_path(tmp_path: Path) -> None:
    task = _make_task()
    mr_url = "https://gitlab.services.mts.ru/foo/bar/-/merge_requests/17"

    push_ok = _completed_process(returncode=0, stdout="", stderr="")
    mr_ok = _completed_process(returncode=0, stdout=f"Merge request created\n{mr_url}\n")

    with patch("subprocess.run", side_effect=[push_ok, mr_ok]):
        result = open_mr_for_task(task=task, worktree_path=tmp_path)

    assert result.ok is True
    assert result.pr_url == mr_url
    assert result.pr_number == 17
    assert result.branch == "whilly/TASK-001"
    assert result.failure_mode == ""


def test_open_mr_for_task_custom_branch_and_title(tmp_path: Path) -> None:
    task = _make_task()
    push_ok = _completed_process(returncode=0)
    mr_ok = _completed_process(
        returncode=0,
        stdout="https://gitlab.example.com/g/p/-/merge_requests/3\n",
    )

    with patch("subprocess.run", side_effect=[push_ok, mr_ok]):
        result = open_mr_for_task(
            task=task,
            worktree_path=tmp_path,
            branch_name="custom/branch",
            title="My custom title",
        )

    assert result.ok is True
    assert result.branch == "custom/branch"


# ── push failures ─────────────────────────────────────────────────────────────


def test_open_mr_for_task_push_timeout(tmp_path: Path) -> None:
    task = _make_task()
    with patch("subprocess.run", side_effect=subprocess.TimeoutExpired(cmd="git push", timeout=60)):
        result = open_mr_for_task(task=task, worktree_path=tmp_path)

    assert result.ok is False
    assert result.failure_mode == "git_push_timeout"
    assert "timeout" in result.reason.lower()


def test_open_mr_for_task_push_failed(tmp_path: Path) -> None:
    task = _make_task()
    push_fail = _completed_process(returncode=1, stderr="remote: Permission denied", stdout="")

    with patch("subprocess.run", return_value=push_fail):
        result = open_mr_for_task(task=task, worktree_path=tmp_path)

    assert result.ok is False
    assert result.failure_mode == "git_push_failed"
    assert result.push_exit_code == 1
    assert "git push failed" in result.reason


def test_open_mr_for_task_no_diff(tmp_path: Path) -> None:
    task = _make_task()
    push_up_to_date = _completed_process(returncode=1, stderr="Everything up-to-date", stdout="")

    with patch("subprocess.run", return_value=push_up_to_date):
        result = open_mr_for_task(task=task, worktree_path=tmp_path)

    assert result.ok is False
    assert result.failure_mode == "no_diff"


# ── MR create failures ────────────────────────────────────────────────────────


def test_open_mr_for_task_mr_create_timeout(tmp_path: Path) -> None:
    task = _make_task()
    push_ok = _completed_process(returncode=0)

    def _side_effect(*args, **kwargs):
        cmd = args[0] if args else kwargs.get("args", [])
        if "push" in cmd:
            return push_ok
        raise subprocess.TimeoutExpired(cmd="glab mr create", timeout=60)

    with patch("subprocess.run", side_effect=_side_effect):
        result = open_mr_for_task(task=task, worktree_path=tmp_path)

    assert result.ok is False
    assert result.failure_mode == "mr_create_timeout"


def test_open_mr_for_task_mr_create_failed(tmp_path: Path) -> None:
    task = _make_task()
    push_ok = _completed_process(returncode=0)
    mr_fail = _completed_process(returncode=1, stderr="fatal: repository not found", stdout="")

    with patch("subprocess.run", side_effect=[push_ok, mr_fail]):
        result = open_mr_for_task(task=task, worktree_path=tmp_path)

    assert result.ok is False
    assert result.failure_mode == "mr_create_failed"
    assert result.gh_exit_code == 1
    assert "glab mr create failed" in result.reason


def test_open_mr_for_task_mr_already_exists_extracts_url(tmp_path: Path) -> None:
    task = _make_task()
    push_ok = _completed_process(returncode=0)
    existing_url = "https://gitlab.services.mts.ru/foo/bar/-/merge_requests/5"
    mr_exists = _completed_process(
        returncode=1,
        stderr=f"A merge request already exists for this branch: {existing_url}",
        stdout="",
    )

    with patch("subprocess.run", side_effect=[push_ok, mr_exists]):
        result = open_mr_for_task(task=task, worktree_path=tmp_path)

    assert result.ok is True
    assert result.reason == "mr already existed"
    assert result.pr_number == 5


# ── worktree_missing ──────────────────────────────────────────────────────────


def test_open_mr_for_task_missing_worktree() -> None:
    task = _make_task()
    non_existent = Path("/tmp/__whilly_test_does_not_exist__")

    result = open_mr_for_task(task=task, worktree_path=non_existent)

    assert result.ok is False
    assert result.failure_mode == "worktree_missing"
    assert "worktree not found" in result.reason


# ── PRResult shape compatibility ──────────────────────────────────────────────


def test_open_mr_for_task_returns_pr_result_instance(tmp_path: Path) -> None:
    """open_mr_for_task must return a PRResult regardless of outcome."""
    task = _make_task()
    with patch("subprocess.run", side_effect=subprocess.TimeoutExpired(cmd="git", timeout=1)):
        result = open_mr_for_task(task=task, worktree_path=tmp_path)
    assert isinstance(result, PRResult)
