"""Generate local Docker env files and print a runnable Whilly setup runbook."""

from __future__ import annotations

import argparse
import platform
import secrets
import shutil
import subprocess
import sys
from collections.abc import Callable, Sequence
from datetime import datetime, timezone
from pathlib import Path

UTC = timezone.utc

try:
    from whilly import __version__
except Exception:  # pragma: no cover - defensive fallback for source-tree use.
    __version__ = "dev"


EXIT_OK = 0
EXIT_USAGE = 2

CONTROL_COMPOSE_FILE = "docker-compose.control-plane.yml"
WORKER_COMPOSE_FILE = "docker-compose.worker.yml"

_MIN_PYTHON_MAJOR = 3
_MIN_PYTHON_MINOR = 12
_PYTHON_REQUIRED = f"python{_MIN_PYTHON_MAJOR}.{_MIN_PYTHON_MINOR}"

_REDACTED_KEYS = frozenset(
    {
        "JIRA_API_TOKEN",
        "POSTGRES_PASSWORD",
        "WHILLY_METRICS_TOKEN",
        "WHILLY_WORKER_BOOTSTRAP_TOKEN",
        "ANTHROPIC_API_KEY",
        "OPENROUTER_API_KEY",
        "OPENAI_API_KEY",
        "GROQ_API_KEY",
        "GEMINI_API_KEY",
        "LLM_API_KEY",
    }
)
_GENERATED_SECRET_KEYS = frozenset({"POSTGRES_PASSWORD", "WHILLY_WORKER_BOOTSTRAP_TOKEN"})


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="whilly quick-setup",
        description="Generate local .env files and print Docker startup commands.",
    )
    parser.add_argument("--repo-root", default=".", help="Repo root to write .env files into. Default: current dir.")
    parser.add_argument("--yes", action="store_true", help="Write files without an interactive confirmation.")
    parser.add_argument("--force", action="store_true", help="Overwrite existing .env and .env.worker files.")
    parser.add_argument("--print-only", action="store_true", help="Print the generated files/runbook without writing.")
    parser.add_argument("--show-secrets", action="store_true", help="Print generated secret values in the terminal.")
    parser.add_argument(
        "--compose-command",
        default=None,
        help="Compose command to print, for example 'docker compose' or 'docker-compose'.",
    )
    parser.add_argument(
        "--docker-provider",
        choices=("auto", "colima", "desktop", "linux"),
        default="auto",
        help="Docker provider guidance to print. Default: auto.",
    )
    parser.add_argument("--image", default=f"mshegolev/whilly:{__version__}", help="Whilly Docker image tag.")
    parser.add_argument("--control-url", default="http://host.docker.internal:8000", help="Worker control-plane URL.")
    parser.add_argument("--plan-id", default="demo", help="Initial plan id for the worker to drain.")
    parser.add_argument("--worker-hostname", default="whilly-worker", help="Worker hostname shown in audit logs.")
    parser.add_argument("--jira-url", default="https://your-company.atlassian.net", help="Jira base URL.")
    parser.add_argument("--jira-user", default="you@example.com", help="Jira user email.")
    parser.add_argument("--jira-token", default="CHANGE_ME_JIRA_API_TOKEN", help="Jira API token.")
    parser.add_argument("--bootstrap-token", default=None, help="Control-plane bootstrap token. Generated by default.")
    parser.add_argument("--postgres-password", default=None, help="Postgres password. Generated by default.")
    parser.add_argument("--cli", dest="agent_cli", default="opencode", help="Agent CLI backend for workers.")
    parser.add_argument("--model", default="opencode/big-pickle", help="Agent model for workers.")
    return parser


def _detect_compose_command() -> str:
    if shutil.which("docker"):
        try:
            result = subprocess.run(
                ["docker", "compose", "version"],
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                check=False,
                timeout=5,
            )
        except (OSError, subprocess.TimeoutExpired):
            result = None
        if result is not None and result.returncode == 0:
            return "docker compose"
    if shutil.which("docker-compose"):
        return "docker-compose"
    return "docker compose"


def _check_python_available(
    *,
    err: object,
    which: Callable[[str], str | None] = shutil.which,
    system: str | None = None,
) -> bool:
    """Warn when ``python3.12`` is missing from ``$PATH``.

    Whilly's :file:`pyproject.toml` pins ``requires-python = ">=3.12"``, so the
    host CLI (``pipx install whilly-orchestrator`` / ``whilly`` console script)
    needs a 3.12 interpreter to install at all. Docker workers ship their own
    Python, so we deliberately do not block setup — the generated ``.env``
    files remain useful for the container-only path — but we surface a clear,
    OS-tailored install hint so the operator isn't blindsided later when
    ``pipx`` refuses to resolve a release.

    Returns ``True`` when a suitable interpreter was found, ``False``
    otherwise. The boolean is informational; the caller does not exit on
    ``False``.
    """
    if which(_PYTHON_REQUIRED):
        return True

    err.write(
        f"whilly quick-setup: no '{_PYTHON_REQUIRED}' found on $PATH. "
        f"Whilly requires Python {_MIN_PYTHON_MAJOR}.{_MIN_PYTHON_MINOR}+ for the "
        "host CLI (Docker workers ship their own interpreter).\n"
    )
    err.write("Install Python 3.12 and then `pipx install --python python3.12 whilly-orchestrator`:\n")
    resolved_system = system if system is not None else platform.system()
    if resolved_system == "Darwin":
        err.write("  brew install python@3.12\n")
        err.write("  # or, via pyenv:\n")
        err.write("  pyenv install 3.12 && pyenv local 3.12\n")
    elif resolved_system == "Linux":
        err.write("  # Debian/Ubuntu:\n")
        err.write("  sudo apt update && sudo apt install python3.12 python3.12-venv\n")
        err.write("  # or, via pyenv:\n")
        err.write("  pyenv install 3.12 && pyenv local 3.12\n")
    elif resolved_system == "Windows":
        err.write("  winget install Python.Python.3.12\n")
        err.write("  # or download the official installer from https://www.python.org/downloads/\n")
    else:
        err.write("  Use pyenv or your platform's package manager to install Python 3.12.\n")
    err.flush()
    return False


def _resolve_docker_provider(selected: str) -> str:
    if selected != "auto":
        return selected
    if platform.system() == "Darwin":
        return "colima" if shutil.which("colima") else "desktop"
    return "linux"


def _render_control_env(
    *,
    generated_at: str,
    jira_url: str,
    jira_user: str,
    jira_token: str,
    image: str,
    postgres_password: str,
    bootstrap_token: str,
) -> str:
    return f"""# Generated by whilly quick-setup at {generated_at}
# Local Docker compose config. Do not commit this file.

JIRA_SERVER_URL={jira_url}
JIRA_USERNAME={jira_user}
JIRA_API_TOKEN={jira_token}

WHILLY_BIND_HOST=0.0.0.0
WHILLY_CONTROL_PORT=8000
WHILLY_IMAGE={image}

POSTGRES_USER=whilly
POSTGRES_PASSWORD={postgres_password}
POSTGRES_DB=whilly
POSTGRES_PORT=5432

WHILLY_WORKER_BOOTSTRAP_TOKEN={bootstrap_token}
WHILLY_WORKER_TOKEN=
WHILLY_METRICS_TOKEN=
WHILLY_LOG_LEVEL=INFO
"""


def _render_worker_env(
    *,
    generated_at: str,
    control_url: str,
    image: str,
    bootstrap_token: str,
    worker_hostname: str,
    plan_id: str,
    agent_cli: str,
    model: str,
) -> str:
    return f"""# Generated by whilly quick-setup at {generated_at}
# Local worker config. Do not commit this file.

WHILLY_CONTROL_URL={control_url}
WHILLY_WORKER_BOOTSTRAP_TOKEN={bootstrap_token}
WHILLY_USE_CONNECT_FLOW=1
WHILLY_INSECURE=1

WHILLY_WORKER_HOSTNAME={worker_hostname}
WHILLY_PLAN_ID={plan_id}
WHILLY_IMAGE={image}

CLAUDE_BIN=/opt/whilly/docker/cli_adapter.py
WHILLY_CLI={agent_cli}
WHILLY_MODEL={model}
WHILLY_FORCE_COMPLETE=1

ANTHROPIC_API_KEY=
OPENROUTER_API_KEY=
OPENAI_API_KEY=
GROQ_API_KEY=
GEMINI_API_KEY=
OPENCODE_DEFAULT_PROVIDER=

LLM_PROVIDER=
LLM_BASE_URL=
LLM_API_KEY=
LLM_MODEL=
LLM_TIER_OVERRIDE=
LLM_TIMEOUT=120
LLM_TEMPERATURE=0
LLM_HTTP_REFERER=
LLM_X_TITLE=
LLM_FORCE_COMPLETE=0
WHILLY_LOG_LEVEL=INFO
"""


def _redact_env(content: str) -> str:
    lines: list[str] = []
    for line in content.splitlines():
        if "=" not in line or line.lstrip().startswith("#"):
            lines.append(line)
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        if key in _GENERATED_SECRET_KEYS:
            lines.append(f"{key}=<generated>")
        elif key in _REDACTED_KEYS and value:
            lines.append(f"{key}=<configured>")
        else:
            lines.append(line)
    return "\n".join(lines) + "\n"


def _write_runbook(
    *,
    out: object,
    repo_root: Path,
    env_content: str,
    worker_env_content: str,
    compose_command: str,
    docker_provider: str,
    print_only: bool,
    show_secrets: bool,
) -> None:
    if print_only:
        out.write("Whilly quick setup preview; no files were written.\n\n")
    else:
        out.write("Whilly quick setup wrote local files:\n")
        out.write(f"  {repo_root / '.env'}\n")
        out.write(f"  {repo_root / '.env.worker'}\n\n")
    out.write(f"Compose command: {compose_command}\n")
    out.write(
        "Secret values are hidden in this terminal output. "
        "Pass --show-secrets only in a private shell if you need to print them.\n\n"
        if not show_secrets
        else "Secret values are shown because --show-secrets was passed.\n\n"
    )
    rendered_env = env_content if show_secrets else _redact_env(env_content)
    rendered_worker_env = worker_env_content if show_secrets else _redact_env(worker_env_content)
    out.write("# .env\n")
    out.write(rendered_env)
    out.write("\n# .env.worker\n")
    out.write(rendered_worker_env)
    out.write("\n")

    if docker_provider == "colima":
        out.write("macOS Colima prep:\n")
        out.write("  colima start\n")
        out.write("  docker context use colima\n")
        out.write("  export DOCKER_HOST=\"$(docker context inspect colima --format '{{.Endpoints.docker.Host}}')\"\n")
        out.write("  export TESTCONTAINERS_RYUK_DISABLED=true\n\n")
    elif docker_provider == "desktop":
        out.write("macOS Docker Desktop prep:\n")
        out.write("  open -a Docker\n")
        out.write("  docker ps\n\n")

    out.write("Start control plane:\n")
    out.write(f"  {compose_command} --env-file .env -f {CONTROL_COMPOSE_FILE} up -d\n")
    out.write(f"  {compose_command} --env-file .env -f {CONTROL_COMPOSE_FILE} ps\n")
    out.write("  curl -fsS http://127.0.0.1:8000/health\n\n")
    out.write("Start worker:\n")
    out.write(f"  {compose_command} --env-file .env.worker -f {WORKER_COMPOSE_FILE} up -d\n")
    out.write(f"  {compose_command} --env-file .env.worker -f {WORKER_COMPOSE_FILE} logs -f worker\n\n")
    out.write("Import a Jira issue when credentials are configured:\n")
    out.write(
        f"  {compose_command} --env-file .env -f {CONTROL_COMPOSE_FILE} exec "
        "-e JIRA_SERVER_URL -e JIRA_USERNAME -e JIRA_API_TOKEN "
        "control-plane whilly jira intake ABC-123\n"
    )
    out.flush()


def run_quick_setup_command(
    argv: Sequence[str],
    *,
    stdout: object | None = None,
    stderr: object | None = None,
    compose_probe: Callable[[], str] = _detect_compose_command,
    token_factory: Callable[[int], str] = secrets.token_urlsafe,
    python_probe: Callable[[str], str | None] = shutil.which,
) -> int:
    out = sys.stdout if stdout is None else stdout
    err = sys.stderr if stderr is None else stderr
    parser = _build_parser()
    args = parser.parse_args(list(argv))

    # Surface the Python 3.12 install hint up front. Soft check: we keep
    # going so the operator still gets ``.env`` / ``.env.worker`` for the
    # Docker-only path (workers ship their own interpreter).
    _check_python_available(err=err, which=python_probe)

    repo_root = Path(args.repo_root).expanduser().resolve()
    if not repo_root.exists() or not repo_root.is_dir():
        err.write(f"whilly quick-setup: repo root does not exist or is not a directory: {repo_root}\n")
        err.flush()
        return EXIT_USAGE

    if not args.yes and not args.print_only:
        err.write("whilly quick-setup: pass --yes to write files, or --print-only to preview.\n")
        err.flush()
        return EXIT_USAGE

    env_path = repo_root / ".env"
    worker_env_path = repo_root / ".env.worker"
    existing = [path for path in (env_path, worker_env_path) if path.exists()]
    if existing and not args.force and not args.print_only:
        rendered = ", ".join(path.name for path in existing)
        err.write(f"whilly quick-setup: {rendered} already exists; pass --force to overwrite.\n")
        err.flush()
        return EXIT_USAGE

    bootstrap_token = args.bootstrap_token or token_factory(24)
    postgres_password = args.postgres_password or token_factory(18)
    generated_at = datetime.now(UTC).isoformat(timespec="seconds")
    env_content = _render_control_env(
        generated_at=generated_at,
        jira_url=args.jira_url,
        jira_user=args.jira_user,
        jira_token=args.jira_token,
        image=args.image,
        postgres_password=postgres_password,
        bootstrap_token=bootstrap_token,
    )
    worker_env_content = _render_worker_env(
        generated_at=generated_at,
        control_url=args.control_url,
        image=args.image,
        bootstrap_token=bootstrap_token,
        worker_hostname=args.worker_hostname,
        plan_id=args.plan_id,
        agent_cli=args.agent_cli,
        model=args.model,
    )

    compose_command = args.compose_command or compose_probe() or "docker compose"
    docker_provider = _resolve_docker_provider(args.docker_provider)

    if not args.print_only:
        env_path.write_text(env_content, encoding="utf-8")
        worker_env_path.write_text(worker_env_content, encoding="utf-8")

    _write_runbook(
        out=out,
        repo_root=repo_root,
        env_content=env_content,
        worker_env_content=worker_env_content,
        compose_command=compose_command,
        docker_provider=docker_provider,
        print_only=bool(args.print_only),
        show_secrets=bool(args.show_secrets),
    )
    return EXIT_OK
